[package]
name = "bracket-embedding"
version = "0.8.7"
edition = "2021"
publish = true
description = "Provides resource embedding services for bracket-lib"
homepage = "https://github.com/thebracket/bracket-lib"
repository = "https://github.com/thebracket/bracket-lib"
readme = "README.md"
keywords = ["roguelike", "gamedev", "terminal", "ascii", "cp437"]
categories = ["game-engines"]
license = "MIT"

[dependencies]
parking_lot = { version = "~0.12" }
lazy_static = "1.4.0"
